const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

class ReportService {
  static async generateReport(reportData, settings = {}) {
    return new Promise((resolve, reject) => {
      try {
        const uploadsDir = path.join(__dirname, '..', 'uploads', 'reports');
        if (!fs.existsSync(uploadsDir)) {
          fs.mkdirSync(uploadsDir, { recursive: true });
        }

        const fileName = `ai-report-${Date.now()}.pdf`;
        const filePath = path.join(uploadsDir, fileName);

        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        const orgName = settings?.organizationName || 'Prosperity Party Dire Dawa Branch Office';

        doc.fontSize(20).font('Helvetica-Bold').text(orgName, { align: 'center' });
        doc.moveDown(0.3);
        doc.fontSize(14).font('Helvetica').text('Membership Fee Management System', { align: 'center' });
        doc.moveDown(0.3);
        doc.fontSize(16).font('Helvetica-Bold').text('AI-Generated Report', { align: 'center' });
        doc.moveDown(0.5);

        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(0.5);

        if (reportData.title) {
          doc.fontSize(14).font('Helvetica-Bold').text(reportData.title);
          doc.moveDown(0.3);
        }

        if (reportData.summary) {
          doc.fontSize(11).font('Helvetica').text(reportData.summary);
          doc.moveDown(0.5);
        }

        if (reportData.sections) {
          for (const section of reportData.sections) {
            doc.fontSize(13).font('Helvetica-Bold').text(section.heading);
            doc.moveDown(0.2);
            doc.fontSize(10).font('Helvetica').text(section.content);
            doc.moveDown(0.3);
          }
        }

        if (reportData.table && reportData.table.headers && reportData.table.rows) {
          doc.moveDown(0.3);
          const tableTop = doc.y;
          const colWidth = 480 / reportData.table.headers.length;
          const rowHeight = 20;

          doc.fontSize(9).font('Helvetica-Bold');
          reportData.table.headers.forEach((h, i) => {
            doc.text(h, 50 + i * colWidth, tableTop, { width: colWidth, align: 'left' });
          });
          doc.moveTo(50, tableTop + 15).lineTo(530, tableTop + 15).stroke();

          reportData.table.rows.forEach((row, ri) => {
            const y = tableTop + 20 + ri * rowHeight;
            if (y > 700) {
              doc.addPage();
            }
            doc.fontSize(8).font('Helvetica');
            row.forEach((cell, ci) => {
              doc.text(String(cell), 50 + ci * colWidth, y, { width: colWidth, align: 'left' });
            });
            if (ri < reportData.table.rows.length - 1) {
              doc.moveTo(50, y + rowHeight - 2).lineTo(530, y + rowHeight - 2).strokeColor('#ccc').stroke();
            }
          });
          doc.y = tableTop + 25 + reportData.table.rows.length * rowHeight;
        }

        if (reportData.totals) {
          doc.moveDown(0.5);
          doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
          doc.moveDown(0.3);
          doc.fontSize(11).font('Helvetica-Bold');
          for (const [key, val] of Object.entries(reportData.totals)) {
            doc.text(`${key}: ${val}`);
          }
        }

        doc.moveDown(1);
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(0.3);
        doc.fontSize(8).font('Helvetica-Oblique').text(
          `Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`,
          { align: 'center' }
        );
        doc.fontSize(8).font('Helvetica').text('This report was automatically generated by AI Assistant.', { align: 'center' });

        doc.end();
        stream.on('finish', () => resolve({ fileName, filePath }));
        stream.on('error', reject);
      } catch (error) {
        reject(error);
      }
    });
  }
}

module.exports = ReportService;
