mversion: 1
services:
  - type: web
    name: mcms-app
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SSL
        value: "true"
      - key: DB_SYNC
        value: "true"
      - key: JWT_SECRET
        generateValue: true
