version: 1
services:
  - type: web
    name: mfc-pp-dd-branch-app
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && node frontend/scripts/generate-icons.cjs; npm run build --prefix frontend && cp frontend/public/manifest.json frontend/dist/manifest.json && cp frontend/public/service-worker.js frontend/dist/service-worker.js && cp -r frontend/public/icons frontend/dist/icons && npm install --prefix backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SSL
        value: "true"
      - key: DB_SYNC
        value: "true"
      - key: JWT_SECRET
        generateValue: true
