import api from '../lib/api'
import type { AIStructuredResponse } from '../hooks/useAIStream'

const ORG_NAME = 'Prosperity Party'
const BRANCH_NAME = 'Dire Dawa Branch Office'
const FOOTER_TEXT = 'Generated by Enterprise AI Copilot'

function fmt(v: any): string {
  if (v === null || v === undefined) return '\u2014'
  return String(v)
}

function col(k: string): string {
  return k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())
}

interface UserInfo {
  fullName?: string
  role?: string
  sectorUnitId?: number
}

function sanitizeData(data: AIStructuredResponse, user?: UserInfo): AIStructuredResponse {
  const sanitized = { ...data }
  if (sanitized.tableData) {
    sanitized.tableData = sanitized.tableData.map((row: any) => {
      const clean: Record<string, any> = {}
      for (const [k, v] of Object.entries(row)) {
        if (k !== 'id' && k !== 'membersList' && k !== '__raw') clean[k] = v
      }
      return clean
    })
  }
  return sanitized
}

function isFieldAllowed(field: string, user?: UserInfo): boolean {
  if (!user) return true
  if (user.role === 'admin' || user.role === 'super_admin') return true
  if (field === 'sectorUnitId' || field === 'sectorId') {
    return String(user.sectorUnitId) === '0' || user.sectorUnitId === undefined
  }
  return true
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

async function logExport(data: AIStructuredResponse, format: string, _lang: string) {
  try {
    await api.post('/ai/activity/log', {
      action: 'EXPORT',
      format,
      report: data.title || 'AI Report',
      timestamp: new Date().toISOString()
    })
  } catch {}
}

function nowStr(): string {
  return new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit'
  })
}

function addOrgHeader(doc: any, pageW: number, margin: number): number {
  let y = margin
  doc.setFontSize(14)
  doc.setTextColor(11, 93, 59)
  doc.text(ORG_NAME, pageW / 2, y, { align: 'center' })
  y += 6
  doc.setFontSize(11)
  doc.setTextColor(212, 175, 55)
  doc.text(BRANCH_NAME, pageW / 2, y, { align: 'center' })
  y += 8
  doc.setDrawColor(212, 175, 55)
  doc.setLineWidth(0.8)
  doc.line(margin, y, pageW - margin, y)
  y += 6
  return y
}

export async function exportPDF(
  data: AIStructuredResponse,
  element: HTMLElement | null,
  lang: string,
  user?: UserInfo
) {
  const jsPDF = (await import('jspdf')).default
  const html2canvas = (await import('html2canvas')).default
  const sd = sanitizeData(data, user)

  const doc = new jsPDF('p', 'mm', 'a4')
  const pageW = 210
  const margin = 15
  const contentW = pageW - margin * 2
  let y = margin

  y = addOrgHeader(doc, pageW, margin)

  doc.setFontSize(20)
  doc.setTextColor(245, 158, 11)
  doc.text(sd.title || 'AI Report', margin, y)
  y += 8

  doc.setFontSize(8)
  doc.setTextColor(100, 100, 120)
  doc.text(`Generated: ${nowStr()}`, margin, y)
  y += 4
  if (user?.fullName) {
    doc.text(`Requested by: ${user.fullName}`, margin, y)
    y += 4
  }
  y += 2

  if (sd.summary) {
    doc.setFontSize(10)
    doc.setTextColor(200, 200, 210)
    const lines = doc.splitTextToSize(sd.summary, contentW)
    for (const line of lines) {
      if (y > 270) { doc.addPage(); y = margin + 10; y = addOrgHeader(doc, pageW, margin) }
      doc.text(line, margin, y)
      y += 5
    }
    y += 4
  }

  if (sd.metrics && Object.keys(sd.metrics).length > 0) {
    if (y > 250) { doc.addPage(); y = margin + 10; y = addOrgHeader(doc, pageW, margin) }
    doc.setFontSize(9)
    doc.setTextColor(245, 158, 11)
    doc.text('Key Metrics', margin, y)
    y += 5
    doc.setFontSize(8)
    doc.setTextColor(180, 180, 200)
    for (const [k, v] of Object.entries(sd.metrics)) {
      doc.text(`${col(k)}: ${fmt(v)}`, margin + 3, y)
      y += 4.5
    }
    y += 3
  }

  const recs = sd.recommendations
  if (recs && recs.length > 0) {
    if (y > 240) { doc.addPage(); y = margin + 10; y = addOrgHeader(doc, pageW, margin) }
    doc.setFontSize(9)
    doc.setTextColor(245, 158, 11)
    doc.text('Recommendations', margin, y)
    y += 5
    doc.setFontSize(8)
    doc.setTextColor(180, 180, 200)
    recs.forEach((rec: string, i: number) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, contentW - 6)
      for (const l of lines) {
        if (y > 270) { doc.addPage(); y = margin + 10; y = addOrgHeader(doc, pageW, margin) }
        doc.text(l, margin + 3, y)
        y += 4.5
      }
    })
    y += 3
  }

  const tableData = sd.tableData
  if (tableData && tableData.length > 0) {
    if (y > 240) { doc.addPage(); y = margin + 10; y = addOrgHeader(doc, pageW, margin) }
    doc.setFontSize(9)
    doc.setTextColor(245, 158, 11)
    doc.text('Data Table', margin, y)
    y += 5

    const keys = Object.keys(tableData[0]).filter(k => k !== 'id' && k !== 'membersList')
    const colW = contentW / keys.length
    doc.setFontSize(7)
    doc.setTextColor(200, 200, 220)
    keys.forEach((k, i) => doc.text(col(k), margin + i * colW, y))
    y += 4
    doc.setDrawColor(80, 80, 100)
    doc.line(margin, y, pageW - margin, y)
    y += 2
    doc.setTextColor(160, 160, 180)
    for (const row of tableData) {
      if (y > 270) { doc.addPage(); y = margin + 10; y = addOrgHeader(doc, pageW, margin) }
      keys.forEach((k, i) => doc.text(fmt(row[k]), margin + i * colW, y))
      y += 4
    }
    y += 3
  }

  if (element) {
    try {
      const canvas = await html2canvas(element, {
        backgroundColor: '#0a0c13',
        scale: 2,
        useCORS: true,
        logging: false
      })
      const imgData = canvas.toDataURL('image/png')
      if (y > 220) { doc.addPage(); y = margin + 10; y = addOrgHeader(doc, pageW, margin) }
      const imgH = (canvas.height / canvas.width) * contentW
      doc.addImage(imgData, 'PNG', margin, y, contentW, Math.min(imgH, 120))
    } catch {}
  }

  doc.setFontSize(7)
  doc.setTextColor(100, 100, 120)
  doc.text(FOOTER_TEXT, pageW / 2, 290, { align: 'center' })

  triggerDownload(doc.output('blob'), `${(sd.title || 'report').replace(/\s+/g, '_')}.pdf`)
  logExport(data, 'PDF', lang)
}

export async function exportWord(data: AIStructuredResponse, lang: string, user?: UserInfo) {
  const { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, HeadingLevel, AlignmentType, WidthType } = await import('docx')
  const sd = sanitizeData(data, user)

  const children: any[] = []

  children.push(
    new Paragraph({ children: [new TextRun({ text: ORG_NAME, bold: true, size: 24, color: '0B5D3B' })], alignment: AlignmentType.CENTER, spacing: { after: 40 } }),
    new Paragraph({ children: [new TextRun({ text: BRANCH_NAME, size: 20, color: 'D4AF37' })], alignment: AlignmentType.CENTER, spacing: { after: 200 } }),
    new Paragraph({ children: [new TextRun({ text: sd.title || 'AI Report', bold: true, size: 28, color: 'F59E0B' })], alignment: AlignmentType.CENTER, spacing: { after: 200 } }),
    new Paragraph({ children: [new TextRun({ text: `Generated: ${nowStr()}`, size: 16, color: '888888' })], alignment: AlignmentType.CENTER, spacing: { after: user?.fullName ? 0 : 400 } })
  )

  if (user?.fullName) {
    children.push(new Paragraph({ children: [new TextRun({ text: `Requested by: ${user.fullName}`, size: 16, color: '888888' })], alignment: AlignmentType.CENTER, spacing: { after: 400 } }))
  }

  if (sd.summary) {
    children.push(new Paragraph({ children: [new TextRun({ text: 'Summary', bold: true, size: 22 })], spacing: { before: 200, after: 200 }, heading: HeadingLevel.HEADING_2 }))
    children.push(new Paragraph({ children: [new TextRun({ text: sd.summary, size: 18, color: '444444' })], spacing: { after: 300 } }))
  }

  if (sd.metrics && Object.keys(sd.metrics).length > 0) {
    children.push(new Paragraph({ children: [new TextRun({ text: 'Key Metrics', bold: true, size: 22 })], spacing: { before: 200, after: 200 }, heading: HeadingLevel.HEADING_2 }))
    const metricRows: any[] = [new TableRow({ children: Object.entries(sd.metrics).map(([k]) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: col(k), bold: true, size: 18 })] })] })) })]
    metricRows.push(new TableRow({ children: Object.entries(sd.metrics).map(([, v]) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: fmt(v), size: 18 })] })] })) }))
    children.push(new Table({ rows: metricRows, width: { size: 100, type: WidthType.PERCENTAGE } }))
    children.push(new Paragraph({ spacing: { after: 300 } }))
  }

  const wTableData = sd.tableData
  if (wTableData && wTableData.length > 0) {
    children.push(new Paragraph({ children: [new TextRun({ text: 'Data Table', bold: true, size: 22 })], spacing: { before: 200, after: 200 }, heading: HeadingLevel.HEADING_2 }))
    const keys = Object.keys(wTableData[0]).filter(k => k !== 'id' && k !== 'membersList')
    const rows: any[] = [new TableRow({ children: keys.map(k => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: col(k), bold: true, size: 16, color: 'FFFFFF' })] })], shading: { fill: 'F59E0B' } })) })]
    for (const row of wTableData) {
      rows.push(new TableRow({ children: keys.map(k => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: fmt(row[k]), size: 16 })] })] })) }))
    }
    children.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }))
    children.push(new Paragraph({ spacing: { after: 300 } }))
  }

  const wRecs = sd.recommendations
  if (wRecs && wRecs.length > 0) {
    children.push(new Paragraph({ children: [new TextRun({ text: 'Recommendations', bold: true, size: 22 })], spacing: { before: 200, after: 200 }, heading: HeadingLevel.HEADING_2 }))
    wRecs.forEach((rec: string, i: number) => {
      children.push(new Paragraph({ children: [new TextRun({ text: `${i + 1}. ${rec}`, size: 18, color: '444444' })], spacing: { after: 100 } }))
    })
  }

  children.push(new Paragraph({ spacing: { before: 400 } }))
  children.push(new Paragraph({ children: [new TextRun({ text: FOOTER_TEXT, size: 16, color: 'AAAAAA', italics: true })], alignment: AlignmentType.CENTER }))

  const doc = new Document({ sections: [{ children }] })
  const blob = await Packer.toBlob(doc)
  triggerDownload(blob, `${(sd.title || 'report').replace(/\s+/g, '_')}.docx`)
  logExport(data, 'DOCX', lang)
}

export async function exportExcel(data: AIStructuredResponse, lang: string, user?: UserInfo) {
  const XLSX = await import('xlsx-js-style')
  const wb = XLSX.utils.book_new()
  const sd = sanitizeData(data, user)

  const summaryRows: any[][] = []
  summaryRows.push([ORG_NAME])
  summaryRows.push([BRANCH_NAME])
  summaryRows.push([sd.title || 'AI Report'])
  summaryRows.push([`Generated: ${nowStr()}`])
  if (user?.fullName) summaryRows.push([`Requested by: ${user.fullName}`])
  summaryRows.push([])
  summaryRows.push(['Summary'])
  summaryRows.push([sd.summary || ''])
  summaryRows.push([])
  summaryRows.push(['Key Metrics'])
  if (sd.metrics && Object.keys(sd.metrics).length > 0) {
    summaryRows.push(...Object.entries(sd.metrics).map(([k, v]) => [col(k), v]))
  }
  summaryRows.push([])
  summaryRows.push(['Recommendations'])
  const xRecs = sd.recommendations
  if (xRecs && xRecs.length > 0) {
    summaryRows.push(...xRecs.map((r: string, i: number) => [`${i + 1}. ${r}`]))
  }
  summaryRows.push([])
  summaryRows.push([FOOTER_TEXT])

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows)
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary')

  const xTableData = sd.tableData
  if (xTableData && xTableData.length > 0) {
    const keys = Object.keys(xTableData[0]).filter(k => k !== 'id' && k !== 'membersList')

    const dataSheet = XLSX.utils.json_to_sheet(
      xTableData.map((r: any) => {
        const o: any = {}
        keys.forEach(k => { o[col(k)] = r[k] })
        return o
      })
    )
    XLSX.utils.book_append_sheet(wb, dataSheet, 'Members Data')

    const xChartData = sd.chartData
    if (xChartData && xChartData.length > 0) {
      const chartKeys = Object.keys(xChartData[0]).filter(k => k !== 'id')
      const paymentsSheet = XLSX.utils.json_to_sheet(
        xChartData.map((r: any) => {
          const o: any = {}
          chartKeys.forEach(k => { o[col(k)] = r[k] })
          return o
        })
      )
      XLSX.utils.book_append_sheet(wb, paymentsSheet, 'Payments Data')
    }

    const sectorSheet = XLSX.utils.aoa_to_sheet([
      ['Sector Analytics'],
      ...(sd.metrics ? Object.entries(sd.metrics).map(([k, v]) => [col(k), v]) : [])
    ])
    XLSX.utils.book_append_sheet(wb, sectorSheet, 'Sector Analytics')

    const xForecastRecs = sd.recommendations
    if (xForecastRecs && xForecastRecs.length > 0) {
      const forecastSheet = XLSX.utils.aoa_to_sheet([
        ['Forecast Data'],
        ['Generated', nowStr()],
        [],
        ...xForecastRecs.map((r: string, i: number) => [`Recommendation ${i + 1}`, r])
      ])
      XLSX.utils.book_append_sheet(wb, forecastSheet, 'Forecast Data')
    }
  }

  XLSX.writeFile(wb, `${(sd.title || 'report').replace(/\s+/g, '_')}.xlsx`)
  logExport(data, 'XLSX', lang)
}

export async function exportCSV(
  data: AIStructuredResponse,
  lang: string,
  exportType?: 'table' | 'filtered' | 'search',
  user?: UserInfo
) {
  const XLSX = await import('xlsx-js-style')
  const sd = sanitizeData(data, user)

  let csv = ''
  const csvTableData = sd.tableData
  if (csvTableData && csvTableData.length > 0) {
    const keys = Object.keys(csvTableData[0]).filter(k => k !== 'id' && k !== 'membersList')
    const ws = XLSX.utils.json_to_sheet(
      csvTableData.map((r: any) => {
        const o: any = {}
        keys.forEach(k => { o[col(k)] = r[k] })
        return o
      })
    )
    csv = XLSX.utils.sheet_to_csv(ws)
  } else {
    const ws = XLSX.utils.aoa_to_sheet([
      [ORG_NAME],
      [BRANCH_NAME],
      [sd.title || 'AI Report'],
      [sd.summary || '']
    ])
    csv = XLSX.utils.sheet_to_csv(ws)
  }

  const suffix = exportType === 'filtered' ? '_filtered' : exportType === 'search' ? '_search' : ''
  triggerDownload(
    new Blob([csv], { type: 'text/csv;charset=utf-8;' }),
    `${(sd.title || 'report').replace(/\s+/g, '_')}${suffix}.csv`
  )
  logExport(data, 'CSV', lang)
}
